workflows:
  build-termux:
    name: Build Termux APK
    max_build_duration: 30
    environment:
      java: 11
    scripts:
      - name: Make gradlew executable
        script: chmod +x ./gradlew

      - name: Build APK (with automatic NDK download)
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
